### ISSUE TITLE
Error when trying to use the library

### ISSUE THREAD

**Issue by oren** [jbmusso/gremlin-client#12]
```
var gremlin = require('gremlin-client');
var client = gremlin.createClient(8182, 'localhost');

var query = client.stream('g.V()');

query.on('data', function(result) {
  // Handle first vertex
  console.log(result);
});

query.on('end', function() {
  console.log("All results fetched");
});
```

```
node index.js
module.js:338
    throw err;
              ^
              Error: Cannot find module 'lodash.isArray'
                  at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:286:25)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/tmp/foo/node_modules/gremlin-client/src/executehandler.js:4:12)
      at Module._compile (module.js:430:26)
      at Object.Module._extensions..js (module.js:448:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
```

**Comment by jbmusso** [comment]
Did you install the library via npm? I can't reproduce this behavior. This is weird, I may have to update the lodash dependencies in package.json.

**Comment by oren** [comment]
I pushed it here (including the node_modules folder): https://github.com/oren/test-gremlin-client

btw, I use io.js v2.5.0

**Comment by tomjakubowski** [comment]
This is an issue on Linux (specifically, an issue on case-sensitive filesystems like ext4). See #13 for a fix.

**Comment by oren** [comment]
:+1:
